[package]
name = "voxcpm_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { path = "../burn/crates/burn",  features = ["wgpu", "tch"] }
burn-import = { path = "../burn/crates/burn-import", features = ["pytorch"]}
burn-store = { path = "../burn/crates/burn-store", features = ["pytorch"]}
hound = "3.5.1"
tokenizers = "0.22.1"

