[package]
name = "voxcpm_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.21.0", features = ["tch", "fusion"] }
burn-store = { version = "0.21.0", default-features = false, features = ["std", "burnpack", "memmap"] }
hound = "3.5.1"
tokenizers = "0.22.1"
kdam = "0.6.3"
clap = { version = "4.5.53", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
tch = "0.22.0"
axum = { version = "0.8.1", features = ["multipart"] }
bytes = "1.10.1"
rand = "0.9.2"
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["full"] }
tower = "0.5.2"
tokio-stream = "0.1.17"
chrono = { version = "0.4.41", default-features = false, features = ["clock"] }

[features]
convert = ["burn-store/pytorch", "burn-store/safetensors"]

[[bin]]
name = "voxcpm-convert"
path = "src/bin/voxcpm-convert.rs"
required-features = ["convert"]

#[patch.crates-io]
#tch = { path = "../tch-rs"}
#torch-sys = { path = "../tch-rs/torch-sys"}
