# Python 3.12 w/ ROCm 7.1.1
FROM docker.io/rocm/pytorch:rocm7.1.1_ubuntu24.04_py3.12_pytorch_release_2.9.1 AS build

# Install Pre-reqs
RUN apt-get update && apt-get install --no-install-recommends -y \
    git vim nano build-essential rustup && \
    rustup default stable && \
    mkdir /app

COPY . /app/

WORKDIR /app

RUN cargo build --release


FROM docker.io/rocm/pytorch:rocm7.1.1_ubuntu24.04_py3.12_pytorch_release_2.9.1 AS release

ENV LIBTORCH=/opt/venv/lib/python3.12/site-packages/torch \
    TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1 \
    TORCH_BLAS_PREFER_HIPBLASLT=1 \
    MIOPEN_FIND_MODE=2 \
    LD_LIBRARY_PATH=/opt/venv/lib/python3.12/site-packages/torch/lib:$LD_LIBRARY_PATH

COPY --from=build /app/target/release/* /app/

COPY voices static burn-models LICENSE /app/

COMMAND ["voxcpm-server"]
